name = "A New Age"
author = "jack"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "292409e27c7ad984d738b2fd00203c0d8b29f1ec2e2a9e2c69305c10d939456c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
