name = "A New Age"
author = "jack"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9885d2654f551cfefb11aca564a9afa8a9dd67dc930df520c04769f680326750"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
