name = "A New Age"
author = "jack"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2236bd78bb7a872871d2481da6356fa75e865826c342b4c8de47eb2566ae57f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
